name: Build
on:
  release:
    types: [published]
jobs:
  push-docker-image:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build latest
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64
          push: true
          build-args: |
            VERSION=${{ github.ref_name }}
          tags: |
            ghcr.io/${{ github.actor }}/naive_proxy:latest
            ghcr.io/${{ github.actor }}/naive_proxy:${{ github.ref_name }}
  test-docker-image:
     needs: [push-docker-image]
     runs-on: ubuntu-22.04
     steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Test Docker image
        run: |
          docker run --rm --entrypoint /usr/bin/naive ghcr.io/${{ github.actor }}/naive_proxy:latest --version
          docker run --rm --entrypoint /usr/bin/naive ghcr.io/${{ github.actor }}/naive_proxy:${{ github.ref_name }} --version